import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "../component/Navbar";
import { SidebarProvider } from "../component/SideNavProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <SidebarProvider>

          <div className="bg-white h-screen ">

            <NavBar />
            {children}

            </div>
         </SidebarProvider>

       </body>
    </html>
  );
}
